pg.add_init_script("if(!localStorage.getItem('trade.log:journal_entries')) localStorage.setItem('trade.log:journal_entries', JSON.stringify({T2:{plan_stop:2.9,plan_target:null,setup:'Breakout',mistakes:['Chased entry','FOMO'],followed_rules:false,notes:'',updated:'x'}}))")
pg.goto("http://localhost:8788/daily.html?date=2026-09-18"); pg.wait_for_timeout(2500)
print("summary:", pg.inner_text("#dn-summary"))
pg.fill("#dn-maxloss","10"); pg.fill("#dn-goal","50"); pg.fill("#dn-plan","Trade only gappers")
pg.locator("#dn-checklist input[type=checkbox]").first.check()
pg.fill("#dn-check-new","No trades after 11"); pg.press("#dn-check-new","Enter")
pg.click('#dn-followed [data-v="no"]')
pg.fill("#dn-well","patience"); pg.fill("#dn-fix","sizing"); pg.fill("#dn-tomorrow","half size")
pg.wait_for_timeout(1200)
print("summary2:", pg.inner_text("#dn-summary"))
print("week foot:", pg.inner_text("#dn-week-foot"))
print("stored:", pg.evaluate("localStorage.getItem('trade.log:daily_notes')")[:400])
pg.click("#dn-next"); pg.wait_for_timeout(600); print("next date:", pg.input_value("#dn-date"), "plan cleared:", repr(pg.input_value("#dn-plan")))
pg.click("#dn-prev"); pg.wait_for_timeout(600); print("back plan:", pg.input_value("#dn-plan"), "checklist:", pg.inner_text("#dn-checklist").replace("\n"," | ")[:200])
pg.reload(); pg.wait_for_timeout(2500); print("after reload tomorrow:", pg.input_value("#dn-tomorrow"))
print("kv keys:", pg.evaluate("window.__db.user_kv.map(r=>r.key)"))
