pg.goto("http://localhost:8788/trade.html?id=T1"); pg.wait_for_timeout(2500)
print("card present:", pg.locator("#jn-stop").count())
if pg.locator("#jn-stop").count():
    pg.fill("#jn-stop","4.80"); pg.fill("#jn-target","5.60")
    pg.click('[data-rules="Yes"]'); pg.click('[data-setup="Breakout"]'); pg.click('[data-mistake="Chased entry"]')
    pg.fill("#jn-setup-new","Gap fill"); pg.press("#jn-setup-new","Enter")
    pg.fill("#jn-mistake-new","Sloppy fill"); pg.press("#jn-mistake-new","Enter")
    pg.fill("#jn-notes","test note"); pg.wait_for_timeout(1500)
    print("metrics:", pg.inner_text("#jn-metrics"))
    print("local:", pg.evaluate("localStorage.getItem('trade.log:journal_entries')"))
    print("kv rows:", json.dumps(pg.evaluate("window.__db.user_kv")))
    pg.reload(); pg.wait_for_timeout(2000)
    print("after reload stop:", pg.input_value("#jn-stop"), "notes:", pg.input_value("#jn-notes"))
    print("setups:", pg.inner_text("#jn-setups")[:120])
